
[build]
rustflags = [
    "-Ctarget-feature=+sse,+avx"
    # "-Ctarget-feature=+adx,+aes,+avx,+avx2,+bmi1,+bmi2,+cmpxchg16b,+f16c,+fma,+fxsr,+gfni,+lzcnt,+movbe,+pclmulqdq,+popcnt,+rdrand,+rdseed,+sha,+sse,+sse2,+sse3,+sse4.1,+sse4.2,+ssse3,+vaes,+vpclmulqdq,+xsave,+xsavec,+xsaveopt,+xsaves"
]
